[package]
name = "rsa_zkps_impl"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.6"
zk-paillier = "0.4.0"
primes = "0.3.0"

[dependencies.curv]
package = "curv-kzen"
version = "0.7"
default-features = false

[dependencies.paillier]
package = "kzen-paillier"
version = "0.4"
default-features = false
