* Attempt 1
verify0                 time:   [2.3781 ms 2.3823 ms 2.3871 ms]
Found 12 outliers among 100 measurements (12.00%)
  3 (3.00%) high mild
  9 (9.00%) high severe

Benchmarking prover1: Warming up for 3.0000 s
Warning: Unable to complete 100 samples in 5.0s. You may wish to increase target time to 19.4s, or reduce sample count to 20.
prover1                 time:   [194.12 ms 194.84 ms 195.77 ms]
Found 7 outliers among 100 measurements (7.00%)
  3 (3.00%) high mild
  4 (4.00%) high severe

verify1                 time:   [109.60 ns 110.00 ns 110.55 ns]
Found 15 outliers among 100 measurements (15.00%)
  5 (5.00%) high mild
  10 (10.00%) high severe

prove2                  time:   [22.284 us 22.345 us 22.416 us]
Found 11 outliers among 100 measurements (11.00%)
  2 (2.00%) high mild
  9 (9.00%) high severe

Benchmarking verify2: Warming up for 3.0000 s
Warning: Unable to complete 100 samples in 5.0s. You may wish to increase target time to 38.8s, or reduce sample count to 10.
verify2                 time:   [387.82 ms 388.35 ms 388.93 ms]
Found 6 outliers among 100 measurements (6.00%)
  2 (2.00%) high mild
  4 (4.00%) high severe
* Attempt 2
verify0                 time:   [2.3813 ms 2.4028 ms 2.4291 ms]
                        change: [-0.0386% +0.8622% +2.1406%] (p = 0.11 > 0.05)
                        No change in performance detected.
Found 10 outliers among 100 measurements (10.00%)
  3 (3.00%) high mild
  7 (7.00%) high severe

Benchmarking prover1: Warming up for 3.0000 s
Warning: Unable to complete 100 samples in 5.0s. You may wish to increase target time to 24.7s, or reduce sample count to 20.
prover1                 time:   [215.56 ms 222.75 ms 230.36 ms]
                        change: [+10.230% +14.322% +18.100%] (p = 0.00 < 0.05)
                        Performance has regressed.
Found 2 outliers among 100 measurements (2.00%)
  2 (2.00%) high mild

verify1                 time:   [107.85 ns 108.24 ns 108.68 ns]
                        change: [-1.7769% -1.1733% -0.5433%] (p = 0.00 < 0.05)
                        Change within noise threshold.
Found 8 outliers among 100 measurements (8.00%)
  4 (4.00%) high mild
  4 (4.00%) high severe

prove2                  time:   [19.714 us 19.923 us 20.189 us]
                        change: [-12.118% -11.297% -10.472%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 8 outliers among 100 measurements (8.00%)
  4 (4.00%) high mild
  4 (4.00%) high severe

Benchmarking verify2: Warming up for 3.0000 s
Warning: Unable to complete 100 samples in 5.0s. You may wish to increase target time to 39.9s, or reduce sample count to 10.
verify2                 time:   [395.97 ms 397.13 ms 398.33 ms]
                        change: [+1.9721% +2.2601% +2.5866%] (p = 0.00 < 0.05)
                        Performance has regressed.
Found 4 outliers among 100 measurements (4.00%)
  4 (4.00%) high mild
* Attempt 3
verify0                 time:   [2.4807 ms 2.5148 ms 2.5535 ms]
                        change: [+2.8962% +4.6603% +6.6352%] (p = 0.00 < 0.05)
                        Performance has regressed.
Found 5 outliers among 100 measurements (5.00%)
  3 (3.00%) high mild
  2 (2.00%) high severe

Benchmarking prover1: Warming up for 3.0000 s
Warning: Unable to complete 100 samples in 5.0s. You may wish to increase target time to 19.5s, or reduce sample count to 20.
prover1                 time:   [194.75 ms 195.35 ms 195.98 ms]
                        change: [-15.225% -12.301% -9.3590%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 2 outliers among 100 measurements (2.00%)
  2 (2.00%) high mild

verify1                 time:   [108.16 ns 108.55 ns 108.98 ns]
                        change: [-1.2115% -0.5631% +0.0354%] (p = 0.09 > 0.05)
                        No change in performance detected.
Found 8 outliers among 100 measurements (8.00%)
  5 (5.00%) high mild
  3 (3.00%) high severe

prove2                  time:   [16.693 us 16.835 us 17.013 us]
                        change: [-13.129% -10.867% -8.1488%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 18 outliers among 100 measurements (18.00%)
  4 (4.00%) high mild
  14 (14.00%) high severe

Benchmarking verify2: Warming up for 3.0000 s
Warning: Unable to complete 100 samples in 5.0s. You may wish to increase target time to 40.1s, or reduce sample count to 10.
verify2                 time:   [400.44 ms 404.13 ms 408.65 ms]
                        change: [+0.7211% +1.7638% +2.9270%] (p = 0.00 < 0.05)
                        Change within noise threshold.
Found 14 outliers among 100 measurements (14.00%)
  3 (3.00%) high mild
  11 (11.00%) high severe
* Attempt 4, w/ random and extended timing
Group 1: Schnorr Paillier/verify0
                        time:   [893.95 ms 899.42 ms 905.35 ms]
Found 9 outliers among 100 measurements (9.00%)
  6 (6.00%) high mild
  3 (3.00%) high severe
Group 1: Schnorr Paillier/prove1
                        time:   [139.91 ms 141.16 ms 142.66 ms]
Found 12 outliers among 100 measurements (12.00%)
  6 (6.00%) high mild
  6 (6.00%) high severe
Group 1: Schnorr Paillier/verify1
                        time:   [80.762 ns 80.918 ns 81.116 ns]
Found 11 outliers among 100 measurements (11.00%)
  6 (6.00%) high mild
  5 (5.00%) high severe
Group 1: Schnorr Paillier/prove2
                        time:   [20.952 us 21.349 us 21.786 us]
Found 7 outliers among 100 measurements (7.00%)
  4 (4.00%) high mild
  3 (3.00%) high severe
Group 1: Schnorr Paillier/verify2
                        time:   [278.29 ms 279.94 ms 281.89 ms]
Found 3 outliers among 100 measurements (3.00%)
  3 (3.00%) high severe
* Attempt 5, comparing to (4)
Group 1: Schnorr Paillier/verify0
                        time:   [880.68 ms 881.10 ms 881.54 ms]
                        change: [-2.6797% -2.0373% -1.4422%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 6 outliers among 100 measurements (6.00%)
  6 (6.00%) high mild
Group 1: Schnorr Paillier/prove1
                        time:   [137.24 ms 137.61 ms 138.04 ms]
                        change: [-3.5749% -2.5177% -1.5974%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 13 outliers among 100 measurements (13.00%)
  4 (4.00%) high mild
  9 (9.00%) high severe
Group 1: Schnorr Paillier/verify1
                        time:   [79.314 ns 79.355 ns 79.398 ns]
                        change: [-3.5669% -2.8254% -2.2214%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 7 outliers among 100 measurements (7.00%)
  4 (4.00%) low mild
  2 (2.00%) high mild
  1 (1.00%) high severe
Group 1: Schnorr Paillier/prove2
                        time:   [21.358 us 21.762 us 22.232 us]
                        change: [-0.8140% +1.9372% +4.8859%] (p = 0.19 > 0.05)
                        No change in performance detected.
Found 11 outliers among 100 measurements (11.00%)
  5 (5.00%) high mild
  6 (6.00%) high severe
Group 1: Schnorr Paillier/verify2
                        time:   [274.19 ms 274.78 ms 275.48 ms]
                        change: [-2.5560% -1.8434% -1.2160%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 5 outliers among 100 measurements (5.00%)
  1 (1.00%) high mild
  4 (4.00%) high severe
